/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpgradeRouteImport } from './routes/upgrade'
import { Route as TreinoRouteImport } from './routes/treino'
import { Route as TafRouteImport } from './routes/taf'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as NutricaoRouteImport } from './routes/nutricao'
import { Route as LojaRouteImport } from './routes/loja'
import { Route as HomeRouteImport } from './routes/home'
import { Route as EvolucaoRouteImport } from './routes/evolucao'
import { Route as ComunidadeRouteImport } from './routes/comunidade'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TreinoConcluidoRouteImport } from './routes/treino.concluido'
import { Route as TreinoAtivoRouteImport } from './routes/treino.ativo'
import { Route as TafSimuladoRouteImport } from './routes/taf.simulado'
import { Route as TafResultadoRouteImport } from './routes/taf.resultado'
import { Route as PerfilNotificacoesRouteImport } from './routes/perfil.notificacoes'
import { Route as PerfilHistoricoRouteImport } from './routes/perfil.historico'
import { Route as PerfilDadosRouteImport } from './routes/perfil.dados'
import { Route as OnboardingSacoRouteImport } from './routes/onboarding.saco'
import { Route as OnboardingProcessandoRouteImport } from './routes/onboarding.processando'
import { Route as OnboardingPreviewRouteImport } from './routes/onboarding.preview'
import { Route as OnboardingObjetivoRouteImport } from './routes/onboarding.objetivo'
import { Route as OnboardingNivelRouteImport } from './routes/onboarding.nivel'
import { Route as OnboardingFrequenciaRouteImport } from './routes/onboarding.frequencia'
import { Route as OnboardingEquipamentosRouteImport } from './routes/onboarding.equipamentos'
import { Route as OnboardingEmailRouteImport } from './routes/onboarding.email'
import { Route as OnboardingCaminhoRouteImport } from './routes/onboarding.caminho'

const UpgradeRoute = UpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const TreinoRoute = TreinoRouteImport.update({
  id: '/treino',
  path: '/treino',
  getParentRoute: () => rootRouteImport,
} as any)
const TafRoute = TafRouteImport.update({
  id: '/taf',
  path: '/taf',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const NutricaoRoute = NutricaoRouteImport.update({
  id: '/nutricao',
  path: '/nutricao',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaRoute = LojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const EvolucaoRoute = EvolucaoRouteImport.update({
  id: '/evolucao',
  path: '/evolucao',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunidadeRoute = ComunidadeRouteImport.update({
  id: '/comunidade',
  path: '/comunidade',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TreinoConcluidoRoute = TreinoConcluidoRouteImport.update({
  id: '/concluido',
  path: '/concluido',
  getParentRoute: () => TreinoRoute,
} as any)
const TreinoAtivoRoute = TreinoAtivoRouteImport.update({
  id: '/ativo',
  path: '/ativo',
  getParentRoute: () => TreinoRoute,
} as any)
const TafSimuladoRoute = TafSimuladoRouteImport.update({
  id: '/simulado',
  path: '/simulado',
  getParentRoute: () => TafRoute,
} as any)
const TafResultadoRoute = TafResultadoRouteImport.update({
  id: '/resultado',
  path: '/resultado',
  getParentRoute: () => TafRoute,
} as any)
const PerfilNotificacoesRoute = PerfilNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => PerfilRoute,
} as any)
const PerfilHistoricoRoute = PerfilHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => PerfilRoute,
} as any)
const PerfilDadosRoute = PerfilDadosRouteImport.update({
  id: '/dados',
  path: '/dados',
  getParentRoute: () => PerfilRoute,
} as any)
const OnboardingSacoRoute = OnboardingSacoRouteImport.update({
  id: '/onboarding/saco',
  path: '/onboarding/saco',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingProcessandoRoute = OnboardingProcessandoRouteImport.update({
  id: '/onboarding/processando',
  path: '/onboarding/processando',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingPreviewRoute = OnboardingPreviewRouteImport.update({
  id: '/onboarding/preview',
  path: '/onboarding/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingObjetivoRoute = OnboardingObjetivoRouteImport.update({
  id: '/onboarding/objetivo',
  path: '/onboarding/objetivo',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingNivelRoute = OnboardingNivelRouteImport.update({
  id: '/onboarding/nivel',
  path: '/onboarding/nivel',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingFrequenciaRoute = OnboardingFrequenciaRouteImport.update({
  id: '/onboarding/frequencia',
  path: '/onboarding/frequencia',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingEquipamentosRoute = OnboardingEquipamentosRouteImport.update({
  id: '/onboarding/equipamentos',
  path: '/onboarding/equipamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingEmailRoute = OnboardingEmailRouteImport.update({
  id: '/onboarding/email',
  path: '/onboarding/email',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingCaminhoRoute = OnboardingCaminhoRouteImport.update({
  id: '/onboarding/caminho',
  path: '/onboarding/caminho',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/comunidade': typeof ComunidadeRoute
  '/evolucao': typeof EvolucaoRoute
  '/home': typeof HomeRoute
  '/loja': typeof LojaRoute
  '/nutricao': typeof NutricaoRoute
  '/perfil': typeof PerfilRouteWithChildren
  '/taf': typeof TafRouteWithChildren
  '/treino': typeof TreinoRouteWithChildren
  '/upgrade': typeof UpgradeRoute
  '/onboarding/caminho': typeof OnboardingCaminhoRoute
  '/onboarding/email': typeof OnboardingEmailRoute
  '/onboarding/equipamentos': typeof OnboardingEquipamentosRoute
  '/onboarding/frequencia': typeof OnboardingFrequenciaRoute
  '/onboarding/nivel': typeof OnboardingNivelRoute
  '/onboarding/objetivo': typeof OnboardingObjetivoRoute
  '/onboarding/preview': typeof OnboardingPreviewRoute
  '/onboarding/processando': typeof OnboardingProcessandoRoute
  '/onboarding/saco': typeof OnboardingSacoRoute
  '/perfil/dados': typeof PerfilDadosRoute
  '/perfil/historico': typeof PerfilHistoricoRoute
  '/perfil/notificacoes': typeof PerfilNotificacoesRoute
  '/taf/resultado': typeof TafResultadoRoute
  '/taf/simulado': typeof TafSimuladoRoute
  '/treino/ativo': typeof TreinoAtivoRoute
  '/treino/concluido': typeof TreinoConcluidoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/comunidade': typeof ComunidadeRoute
  '/evolucao': typeof EvolucaoRoute
  '/home': typeof HomeRoute
  '/loja': typeof LojaRoute
  '/nutricao': typeof NutricaoRoute
  '/perfil': typeof PerfilRouteWithChildren
  '/taf': typeof TafRouteWithChildren
  '/treino': typeof TreinoRouteWithChildren
  '/upgrade': typeof UpgradeRoute
  '/onboarding/caminho': typeof OnboardingCaminhoRoute
  '/onboarding/email': typeof OnboardingEmailRoute
  '/onboarding/equipamentos': typeof OnboardingEquipamentosRoute
  '/onboarding/frequencia': typeof OnboardingFrequenciaRoute
  '/onboarding/nivel': typeof OnboardingNivelRoute
  '/onboarding/objetivo': typeof OnboardingObjetivoRoute
  '/onboarding/preview': typeof OnboardingPreviewRoute
  '/onboarding/processando': typeof OnboardingProcessandoRoute
  '/onboarding/saco': typeof OnboardingSacoRoute
  '/perfil/dados': typeof PerfilDadosRoute
  '/perfil/historico': typeof PerfilHistoricoRoute
  '/perfil/notificacoes': typeof PerfilNotificacoesRoute
  '/taf/resultado': typeof TafResultadoRoute
  '/taf/simulado': typeof TafSimuladoRoute
  '/treino/ativo': typeof TreinoAtivoRoute
  '/treino/concluido': typeof TreinoConcluidoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/comunidade': typeof ComunidadeRoute
  '/evolucao': typeof EvolucaoRoute
  '/home': typeof HomeRoute
  '/loja': typeof LojaRoute
  '/nutricao': typeof NutricaoRoute
  '/perfil': typeof PerfilRouteWithChildren
  '/taf': typeof TafRouteWithChildren
  '/treino': typeof TreinoRouteWithChildren
  '/upgrade': typeof UpgradeRoute
  '/onboarding/caminho': typeof OnboardingCaminhoRoute
  '/onboarding/email': typeof OnboardingEmailRoute
  '/onboarding/equipamentos': typeof OnboardingEquipamentosRoute
  '/onboarding/frequencia': typeof OnboardingFrequenciaRoute
  '/onboarding/nivel': typeof OnboardingNivelRoute
  '/onboarding/objetivo': typeof OnboardingObjetivoRoute
  '/onboarding/preview': typeof OnboardingPreviewRoute
  '/onboarding/processando': typeof OnboardingProcessandoRoute
  '/onboarding/saco': typeof OnboardingSacoRoute
  '/perfil/dados': typeof PerfilDadosRoute
  '/perfil/historico': typeof PerfilHistoricoRoute
  '/perfil/notificacoes': typeof PerfilNotificacoesRoute
  '/taf/resultado': typeof TafResultadoRoute
  '/taf/simulado': typeof TafSimuladoRoute
  '/treino/ativo': typeof TreinoAtivoRoute
  '/treino/concluido': typeof TreinoConcluidoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/comunidade'
    | '/evolucao'
    | '/home'
    | '/loja'
    | '/nutricao'
    | '/perfil'
    | '/taf'
    | '/treino'
    | '/upgrade'
    | '/onboarding/caminho'
    | '/onboarding/email'
    | '/onboarding/equipamentos'
    | '/onboarding/frequencia'
    | '/onboarding/nivel'
    | '/onboarding/objetivo'
    | '/onboarding/preview'
    | '/onboarding/processando'
    | '/onboarding/saco'
    | '/perfil/dados'
    | '/perfil/historico'
    | '/perfil/notificacoes'
    | '/taf/resultado'
    | '/taf/simulado'
    | '/treino/ativo'
    | '/treino/concluido'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/comunidade'
    | '/evolucao'
    | '/home'
    | '/loja'
    | '/nutricao'
    | '/perfil'
    | '/taf'
    | '/treino'
    | '/upgrade'
    | '/onboarding/caminho'
    | '/onboarding/email'
    | '/onboarding/equipamentos'
    | '/onboarding/frequencia'
    | '/onboarding/nivel'
    | '/onboarding/objetivo'
    | '/onboarding/preview'
    | '/onboarding/processando'
    | '/onboarding/saco'
    | '/perfil/dados'
    | '/perfil/historico'
    | '/perfil/notificacoes'
    | '/taf/resultado'
    | '/taf/simulado'
    | '/treino/ativo'
    | '/treino/concluido'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/comunidade'
    | '/evolucao'
    | '/home'
    | '/loja'
    | '/nutricao'
    | '/perfil'
    | '/taf'
    | '/treino'
    | '/upgrade'
    | '/onboarding/caminho'
    | '/onboarding/email'
    | '/onboarding/equipamentos'
    | '/onboarding/frequencia'
    | '/onboarding/nivel'
    | '/onboarding/objetivo'
    | '/onboarding/preview'
    | '/onboarding/processando'
    | '/onboarding/saco'
    | '/perfil/dados'
    | '/perfil/historico'
    | '/perfil/notificacoes'
    | '/taf/resultado'
    | '/taf/simulado'
    | '/treino/ativo'
    | '/treino/concluido'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ComunidadeRoute: typeof ComunidadeRoute
  EvolucaoRoute: typeof EvolucaoRoute
  HomeRoute: typeof HomeRoute
  LojaRoute: typeof LojaRoute
  NutricaoRoute: typeof NutricaoRoute
  PerfilRoute: typeof PerfilRouteWithChildren
  TafRoute: typeof TafRouteWithChildren
  TreinoRoute: typeof TreinoRouteWithChildren
  UpgradeRoute: typeof UpgradeRoute
  OnboardingCaminhoRoute: typeof OnboardingCaminhoRoute
  OnboardingEmailRoute: typeof OnboardingEmailRoute
  OnboardingEquipamentosRoute: typeof OnboardingEquipamentosRoute
  OnboardingFrequenciaRoute: typeof OnboardingFrequenciaRoute
  OnboardingNivelRoute: typeof OnboardingNivelRoute
  OnboardingObjetivoRoute: typeof OnboardingObjetivoRoute
  OnboardingPreviewRoute: typeof OnboardingPreviewRoute
  OnboardingProcessandoRoute: typeof OnboardingProcessandoRoute
  OnboardingSacoRoute: typeof OnboardingSacoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upgrade': {
      id: '/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof UpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treino': {
      id: '/treino'
      path: '/treino'
      fullPath: '/treino'
      preLoaderRoute: typeof TreinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taf': {
      id: '/taf'
      path: '/taf'
      fullPath: '/taf'
      preLoaderRoute: typeof TafRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutricao': {
      id: '/nutricao'
      path: '/nutricao'
      fullPath: '/nutricao'
      preLoaderRoute: typeof NutricaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja': {
      id: '/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof LojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evolucao': {
      id: '/evolucao'
      path: '/evolucao'
      fullPath: '/evolucao'
      preLoaderRoute: typeof EvolucaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidade': {
      id: '/comunidade'
      path: '/comunidade'
      fullPath: '/comunidade'
      preLoaderRoute: typeof ComunidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treino/concluido': {
      id: '/treino/concluido'
      path: '/concluido'
      fullPath: '/treino/concluido'
      preLoaderRoute: typeof TreinoConcluidoRouteImport
      parentRoute: typeof TreinoRoute
    }
    '/treino/ativo': {
      id: '/treino/ativo'
      path: '/ativo'
      fullPath: '/treino/ativo'
      preLoaderRoute: typeof TreinoAtivoRouteImport
      parentRoute: typeof TreinoRoute
    }
    '/taf/simulado': {
      id: '/taf/simulado'
      path: '/simulado'
      fullPath: '/taf/simulado'
      preLoaderRoute: typeof TafSimuladoRouteImport
      parentRoute: typeof TafRoute
    }
    '/taf/resultado': {
      id: '/taf/resultado'
      path: '/resultado'
      fullPath: '/taf/resultado'
      preLoaderRoute: typeof TafResultadoRouteImport
      parentRoute: typeof TafRoute
    }
    '/perfil/notificacoes': {
      id: '/perfil/notificacoes'
      path: '/notificacoes'
      fullPath: '/perfil/notificacoes'
      preLoaderRoute: typeof PerfilNotificacoesRouteImport
      parentRoute: typeof PerfilRoute
    }
    '/perfil/historico': {
      id: '/perfil/historico'
      path: '/historico'
      fullPath: '/perfil/historico'
      preLoaderRoute: typeof PerfilHistoricoRouteImport
      parentRoute: typeof PerfilRoute
    }
    '/perfil/dados': {
      id: '/perfil/dados'
      path: '/dados'
      fullPath: '/perfil/dados'
      preLoaderRoute: typeof PerfilDadosRouteImport
      parentRoute: typeof PerfilRoute
    }
    '/onboarding/saco': {
      id: '/onboarding/saco'
      path: '/onboarding/saco'
      fullPath: '/onboarding/saco'
      preLoaderRoute: typeof OnboardingSacoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/processando': {
      id: '/onboarding/processando'
      path: '/onboarding/processando'
      fullPath: '/onboarding/processando'
      preLoaderRoute: typeof OnboardingProcessandoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/preview': {
      id: '/onboarding/preview'
      path: '/onboarding/preview'
      fullPath: '/onboarding/preview'
      preLoaderRoute: typeof OnboardingPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/objetivo': {
      id: '/onboarding/objetivo'
      path: '/onboarding/objetivo'
      fullPath: '/onboarding/objetivo'
      preLoaderRoute: typeof OnboardingObjetivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/nivel': {
      id: '/onboarding/nivel'
      path: '/onboarding/nivel'
      fullPath: '/onboarding/nivel'
      preLoaderRoute: typeof OnboardingNivelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/frequencia': {
      id: '/onboarding/frequencia'
      path: '/onboarding/frequencia'
      fullPath: '/onboarding/frequencia'
      preLoaderRoute: typeof OnboardingFrequenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/equipamentos': {
      id: '/onboarding/equipamentos'
      path: '/onboarding/equipamentos'
      fullPath: '/onboarding/equipamentos'
      preLoaderRoute: typeof OnboardingEquipamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/email': {
      id: '/onboarding/email'
      path: '/onboarding/email'
      fullPath: '/onboarding/email'
      preLoaderRoute: typeof OnboardingEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/caminho': {
      id: '/onboarding/caminho'
      path: '/onboarding/caminho'
      fullPath: '/onboarding/caminho'
      preLoaderRoute: typeof OnboardingCaminhoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PerfilRouteChildren {
  PerfilDadosRoute: typeof PerfilDadosRoute
  PerfilHistoricoRoute: typeof PerfilHistoricoRoute
  PerfilNotificacoesRoute: typeof PerfilNotificacoesRoute
}

const PerfilRouteChildren: PerfilRouteChildren = {
  PerfilDadosRoute: PerfilDadosRoute,
  PerfilHistoricoRoute: PerfilHistoricoRoute,
  PerfilNotificacoesRoute: PerfilNotificacoesRoute,
}

const PerfilRouteWithChildren =
  PerfilRoute._addFileChildren(PerfilRouteChildren)

interface TafRouteChildren {
  TafResultadoRoute: typeof TafResultadoRoute
  TafSimuladoRoute: typeof TafSimuladoRoute
}

const TafRouteChildren: TafRouteChildren = {
  TafResultadoRoute: TafResultadoRoute,
  TafSimuladoRoute: TafSimuladoRoute,
}

const TafRouteWithChildren = TafRoute._addFileChildren(TafRouteChildren)

interface TreinoRouteChildren {
  TreinoAtivoRoute: typeof TreinoAtivoRoute
  TreinoConcluidoRoute: typeof TreinoConcluidoRoute
}

const TreinoRouteChildren: TreinoRouteChildren = {
  TreinoAtivoRoute: TreinoAtivoRoute,
  TreinoConcluidoRoute: TreinoConcluidoRoute,
}

const TreinoRouteWithChildren =
  TreinoRoute._addFileChildren(TreinoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ComunidadeRoute: ComunidadeRoute,
  EvolucaoRoute: EvolucaoRoute,
  HomeRoute: HomeRoute,
  LojaRoute: LojaRoute,
  NutricaoRoute: NutricaoRoute,
  PerfilRoute: PerfilRouteWithChildren,
  TafRoute: TafRouteWithChildren,
  TreinoRoute: TreinoRouteWithChildren,
  UpgradeRoute: UpgradeRoute,
  OnboardingCaminhoRoute: OnboardingCaminhoRoute,
  OnboardingEmailRoute: OnboardingEmailRoute,
  OnboardingEquipamentosRoute: OnboardingEquipamentosRoute,
  OnboardingFrequenciaRoute: OnboardingFrequenciaRoute,
  OnboardingNivelRoute: OnboardingNivelRoute,
  OnboardingObjetivoRoute: OnboardingObjetivoRoute,
  OnboardingPreviewRoute: OnboardingPreviewRoute,
  OnboardingProcessandoRoute: OnboardingProcessandoRoute,
  OnboardingSacoRoute: OnboardingSacoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
