/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpgradeRouteImport } from './routes/upgrade'
import { Route as TrilhaBarraRouteImport } from './routes/trilha-barra'
import { Route as TreinosSoBarraRouteImport } from './routes/treinos-so-barra'
import { Route as TreinoDoDiaRouteImport } from './routes/treino-do-dia'
import { Route as TreinoRouteImport } from './routes/treino'
import { Route as TafRouteImport } from './routes/taf'
import { Route as SemanaRouteImport } from './routes/semana'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as NutricaoRouteImport } from './routes/nutricao'
import { Route as LojaRouteImport } from './routes/loja'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ExercicioDetalheRouteImport } from './routes/exercicio-detalhe'
import { Route as EvolucaoRouteImport } from './routes/evolucao'
import { Route as DietaRouteImport } from './routes/dieta'
import { Route as ComunidadeRouteImport } from './routes/comunidade'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TreinoConcluidoRouteImport } from './routes/treino.concluido'
import { Route as TreinoAtivoRouteImport } from './routes/treino.ativo'
import { Route as TafSimuladoRouteImport } from './routes/taf.simulado'
import { Route as TafResultadoRouteImport } from './routes/taf.resultado'
import { Route as PerfilNotificacoesRouteImport } from './routes/perfil.notificacoes'
import { Route as PerfilHistoricoRouteImport } from './routes/perfil.historico'
import { Route as PerfilDadosRouteImport } from './routes/perfil.dados'
import { Route as OnboardingProcessandoRouteImport } from './routes/onboarding.processando'
import { Route as OnboardingPreviewRouteImport } from './routes/onboarding.preview'
import { Route as OnboardingPreviaRouteImport } from './routes/onboarding.previa'
import { Route as OnboardingObjetivoRouteImport } from './routes/onboarding.objetivo'
import { Route as OnboardingNivelRouteImport } from './routes/onboarding.nivel'
import { Route as OnboardingFrequenciaRouteImport } from './routes/onboarding.frequencia'
import { Route as OnboardingEquipamentosRouteImport } from './routes/onboarding.equipamentos'
import { Route as OnboardingEmailRouteImport } from './routes/onboarding.email'
import { Route as OnboardingCaminhoRouteImport } from './routes/onboarding.caminho'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiPublicMpPublicKeyRouteImport } from './routes/api/public/mp-public-key'
import { Route as ApiPublicMercadopagoWebhookRouteImport } from './routes/api/public/mercadopago-webhook'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicHooksSendRemindersRouteImport } from './routes/api/public/hooks/send-reminders'
import { Route as ApiPublicExerciseGifIdRouteImport } from './routes/api/public/exercise-gif.$id'
import { Route as ApiPublicExerciseGifByNameNameRouteImport } from './routes/api/public/exercise-gif-by-name.$name'

const UpgradeRoute = UpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const TrilhaBarraRoute = TrilhaBarraRouteImport.update({
  id: '/trilha-barra',
  path: '/trilha-barra',
  getParentRoute: () => rootRouteImport,
} as any)
const TreinosSoBarraRoute = TreinosSoBarraRouteImport.update({
  id: '/treinos-so-barra',
  path: '/treinos-so-barra',
  getParentRoute: () => rootRouteImport,
} as any)
const TreinoDoDiaRoute = TreinoDoDiaRouteImport.update({
  id: '/treino-do-dia',
  path: '/treino-do-dia',
  getParentRoute: () => rootRouteImport,
} as any)
const TreinoRoute = TreinoRouteImport.update({
  id: '/treino',
  path: '/treino',
  getParentRoute: () => rootRouteImport,
} as any)
const TafRoute = TafRouteImport.update({
  id: '/taf',
  path: '/taf',
  getParentRoute: () => rootRouteImport,
} as any)
const SemanaRoute = SemanaRouteImport.update({
  id: '/semana',
  path: '/semana',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const NutricaoRoute = NutricaoRouteImport.update({
  id: '/nutricao',
  path: '/nutricao',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaRoute = LojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercicioDetalheRoute = ExercicioDetalheRouteImport.update({
  id: '/exercicio-detalhe',
  path: '/exercicio-detalhe',
  getParentRoute: () => rootRouteImport,
} as any)
const EvolucaoRoute = EvolucaoRouteImport.update({
  id: '/evolucao',
  path: '/evolucao',
  getParentRoute: () => rootRouteImport,
} as any)
const DietaRoute = DietaRouteImport.update({
  id: '/dieta',
  path: '/dieta',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunidadeRoute = ComunidadeRouteImport.update({
  id: '/comunidade',
  path: '/comunidade',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TreinoConcluidoRoute = TreinoConcluidoRouteImport.update({
  id: '/concluido',
  path: '/concluido',
  getParentRoute: () => TreinoRoute,
} as any)
const TreinoAtivoRoute = TreinoAtivoRouteImport.update({
  id: '/ativo',
  path: '/ativo',
  getParentRoute: () => TreinoRoute,
} as any)
const TafSimuladoRoute = TafSimuladoRouteImport.update({
  id: '/simulado',
  path: '/simulado',
  getParentRoute: () => TafRoute,
} as any)
const TafResultadoRoute = TafResultadoRouteImport.update({
  id: '/resultado',
  path: '/resultado',
  getParentRoute: () => TafRoute,
} as any)
const PerfilNotificacoesRoute = PerfilNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => PerfilRoute,
} as any)
const PerfilHistoricoRoute = PerfilHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => PerfilRoute,
} as any)
const PerfilDadosRoute = PerfilDadosRouteImport.update({
  id: '/dados',
  path: '/dados',
  getParentRoute: () => PerfilRoute,
} as any)
const OnboardingProcessandoRoute = OnboardingProcessandoRouteImport.update({
  id: '/onboarding/processando',
  path: '/onboarding/processando',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingPreviewRoute = OnboardingPreviewRouteImport.update({
  id: '/onboarding/preview',
  path: '/onboarding/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingPreviaRoute = OnboardingPreviaRouteImport.update({
  id: '/onboarding/previa',
  path: '/onboarding/previa',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingObjetivoRoute = OnboardingObjetivoRouteImport.update({
  id: '/onboarding/objetivo',
  path: '/onboarding/objetivo',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingNivelRoute = OnboardingNivelRouteImport.update({
  id: '/onboarding/nivel',
  path: '/onboarding/nivel',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingFrequenciaRoute = OnboardingFrequenciaRouteImport.update({
  id: '/onboarding/frequencia',
  path: '/onboarding/frequencia',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingEquipamentosRoute = OnboardingEquipamentosRouteImport.update({
  id: '/onboarding/equipamentos',
  path: '/onboarding/equipamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingEmailRoute = OnboardingEmailRouteImport.update({
  id: '/onboarding/email',
  path: '/onboarding/email',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingCaminhoRoute = OnboardingCaminhoRouteImport.update({
  id: '/onboarding/caminho',
  path: '/onboarding/caminho',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const ApiPublicMpPublicKeyRoute = ApiPublicMpPublicKeyRouteImport.update({
  id: '/api/public/mp-public-key',
  path: '/api/public/mp-public-key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMercadopagoWebhookRoute =
  ApiPublicMercadopagoWebhookRouteImport.update({
    id: '/api/public/mercadopago-webhook',
    path: '/api/public/mercadopago-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSendRemindersRoute =
  ApiPublicHooksSendRemindersRouteImport.update({
    id: '/api/public/hooks/send-reminders',
    path: '/api/public/hooks/send-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicExerciseGifIdRoute = ApiPublicExerciseGifIdRouteImport.update({
  id: '/api/public/exercise-gif/$id',
  path: '/api/public/exercise-gif/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicExerciseGifByNameNameRoute =
  ApiPublicExerciseGifByNameNameRouteImport.update({
    id: '/api/public/exercise-gif-by-name/$name',
    path: '/api/public/exercise-gif-by-name/$name',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/comunidade': typeof ComunidadeRoute
  '/dieta': typeof DietaRoute
  '/evolucao': typeof EvolucaoRoute
  '/exercicio-detalhe': typeof ExercicioDetalheRoute
  '/home': typeof HomeRoute
  '/loja': typeof LojaRoute
  '/nutricao': typeof NutricaoRoute
  '/perfil': typeof PerfilRouteWithChildren
  '/semana': typeof SemanaRoute
  '/taf': typeof TafRouteWithChildren
  '/treino': typeof TreinoRouteWithChildren
  '/treino-do-dia': typeof TreinoDoDiaRoute
  '/treinos-so-barra': typeof TreinosSoBarraRoute
  '/trilha-barra': typeof TrilhaBarraRoute
  '/upgrade': typeof UpgradeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/onboarding/caminho': typeof OnboardingCaminhoRoute
  '/onboarding/email': typeof OnboardingEmailRoute
  '/onboarding/equipamentos': typeof OnboardingEquipamentosRoute
  '/onboarding/frequencia': typeof OnboardingFrequenciaRoute
  '/onboarding/nivel': typeof OnboardingNivelRoute
  '/onboarding/objetivo': typeof OnboardingObjetivoRoute
  '/onboarding/previa': typeof OnboardingPreviaRoute
  '/onboarding/preview': typeof OnboardingPreviewRoute
  '/onboarding/processando': typeof OnboardingProcessandoRoute
  '/perfil/dados': typeof PerfilDadosRoute
  '/perfil/historico': typeof PerfilHistoricoRoute
  '/perfil/notificacoes': typeof PerfilNotificacoesRoute
  '/taf/resultado': typeof TafResultadoRoute
  '/taf/simulado': typeof TafSimuladoRoute
  '/treino/ativo': typeof TreinoAtivoRoute
  '/treino/concluido': typeof TreinoConcluidoRoute
  '/api/public/mercadopago-webhook': typeof ApiPublicMercadopagoWebhookRoute
  '/api/public/mp-public-key': typeof ApiPublicMpPublicKeyRoute
  '/api/public/exercise-gif-by-name/$name': typeof ApiPublicExerciseGifByNameNameRoute
  '/api/public/exercise-gif/$id': typeof ApiPublicExerciseGifIdRoute
  '/api/public/hooks/send-reminders': typeof ApiPublicHooksSendRemindersRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/comunidade': typeof ComunidadeRoute
  '/dieta': typeof DietaRoute
  '/evolucao': typeof EvolucaoRoute
  '/exercicio-detalhe': typeof ExercicioDetalheRoute
  '/home': typeof HomeRoute
  '/loja': typeof LojaRoute
  '/nutricao': typeof NutricaoRoute
  '/perfil': typeof PerfilRouteWithChildren
  '/semana': typeof SemanaRoute
  '/taf': typeof TafRouteWithChildren
  '/treino': typeof TreinoRouteWithChildren
  '/treino-do-dia': typeof TreinoDoDiaRoute
  '/treinos-so-barra': typeof TreinosSoBarraRoute
  '/trilha-barra': typeof TrilhaBarraRoute
  '/upgrade': typeof UpgradeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/onboarding/caminho': typeof OnboardingCaminhoRoute
  '/onboarding/email': typeof OnboardingEmailRoute
  '/onboarding/equipamentos': typeof OnboardingEquipamentosRoute
  '/onboarding/frequencia': typeof OnboardingFrequenciaRoute
  '/onboarding/nivel': typeof OnboardingNivelRoute
  '/onboarding/objetivo': typeof OnboardingObjetivoRoute
  '/onboarding/previa': typeof OnboardingPreviaRoute
  '/onboarding/preview': typeof OnboardingPreviewRoute
  '/onboarding/processando': typeof OnboardingProcessandoRoute
  '/perfil/dados': typeof PerfilDadosRoute
  '/perfil/historico': typeof PerfilHistoricoRoute
  '/perfil/notificacoes': typeof PerfilNotificacoesRoute
  '/taf/resultado': typeof TafResultadoRoute
  '/taf/simulado': typeof TafSimuladoRoute
  '/treino/ativo': typeof TreinoAtivoRoute
  '/treino/concluido': typeof TreinoConcluidoRoute
  '/api/public/mercadopago-webhook': typeof ApiPublicMercadopagoWebhookRoute
  '/api/public/mp-public-key': typeof ApiPublicMpPublicKeyRoute
  '/api/public/exercise-gif-by-name/$name': typeof ApiPublicExerciseGifByNameNameRoute
  '/api/public/exercise-gif/$id': typeof ApiPublicExerciseGifIdRoute
  '/api/public/hooks/send-reminders': typeof ApiPublicHooksSendRemindersRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/comunidade': typeof ComunidadeRoute
  '/dieta': typeof DietaRoute
  '/evolucao': typeof EvolucaoRoute
  '/exercicio-detalhe': typeof ExercicioDetalheRoute
  '/home': typeof HomeRoute
  '/loja': typeof LojaRoute
  '/nutricao': typeof NutricaoRoute
  '/perfil': typeof PerfilRouteWithChildren
  '/semana': typeof SemanaRoute
  '/taf': typeof TafRouteWithChildren
  '/treino': typeof TreinoRouteWithChildren
  '/treino-do-dia': typeof TreinoDoDiaRoute
  '/treinos-so-barra': typeof TreinosSoBarraRoute
  '/trilha-barra': typeof TrilhaBarraRoute
  '/upgrade': typeof UpgradeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/onboarding/caminho': typeof OnboardingCaminhoRoute
  '/onboarding/email': typeof OnboardingEmailRoute
  '/onboarding/equipamentos': typeof OnboardingEquipamentosRoute
  '/onboarding/frequencia': typeof OnboardingFrequenciaRoute
  '/onboarding/nivel': typeof OnboardingNivelRoute
  '/onboarding/objetivo': typeof OnboardingObjetivoRoute
  '/onboarding/previa': typeof OnboardingPreviaRoute
  '/onboarding/preview': typeof OnboardingPreviewRoute
  '/onboarding/processando': typeof OnboardingProcessandoRoute
  '/perfil/dados': typeof PerfilDadosRoute
  '/perfil/historico': typeof PerfilHistoricoRoute
  '/perfil/notificacoes': typeof PerfilNotificacoesRoute
  '/taf/resultado': typeof TafResultadoRoute
  '/taf/simulado': typeof TafSimuladoRoute
  '/treino/ativo': typeof TreinoAtivoRoute
  '/treino/concluido': typeof TreinoConcluidoRoute
  '/api/public/mercadopago-webhook': typeof ApiPublicMercadopagoWebhookRoute
  '/api/public/mp-public-key': typeof ApiPublicMpPublicKeyRoute
  '/api/public/exercise-gif-by-name/$name': typeof ApiPublicExerciseGifByNameNameRoute
  '/api/public/exercise-gif/$id': typeof ApiPublicExerciseGifIdRoute
  '/api/public/hooks/send-reminders': typeof ApiPublicHooksSendRemindersRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/comunidade'
    | '/dieta'
    | '/evolucao'
    | '/exercicio-detalhe'
    | '/home'
    | '/loja'
    | '/nutricao'
    | '/perfil'
    | '/semana'
    | '/taf'
    | '/treino'
    | '/treino-do-dia'
    | '/treinos-so-barra'
    | '/trilha-barra'
    | '/upgrade'
    | '/auth/callback'
    | '/onboarding/caminho'
    | '/onboarding/email'
    | '/onboarding/equipamentos'
    | '/onboarding/frequencia'
    | '/onboarding/nivel'
    | '/onboarding/objetivo'
    | '/onboarding/previa'
    | '/onboarding/preview'
    | '/onboarding/processando'
    | '/perfil/dados'
    | '/perfil/historico'
    | '/perfil/notificacoes'
    | '/taf/resultado'
    | '/taf/simulado'
    | '/treino/ativo'
    | '/treino/concluido'
    | '/api/public/mercadopago-webhook'
    | '/api/public/mp-public-key'
    | '/api/public/exercise-gif-by-name/$name'
    | '/api/public/exercise-gif/$id'
    | '/api/public/hooks/send-reminders'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/comunidade'
    | '/dieta'
    | '/evolucao'
    | '/exercicio-detalhe'
    | '/home'
    | '/loja'
    | '/nutricao'
    | '/perfil'
    | '/semana'
    | '/taf'
    | '/treino'
    | '/treino-do-dia'
    | '/treinos-so-barra'
    | '/trilha-barra'
    | '/upgrade'
    | '/auth/callback'
    | '/onboarding/caminho'
    | '/onboarding/email'
    | '/onboarding/equipamentos'
    | '/onboarding/frequencia'
    | '/onboarding/nivel'
    | '/onboarding/objetivo'
    | '/onboarding/previa'
    | '/onboarding/preview'
    | '/onboarding/processando'
    | '/perfil/dados'
    | '/perfil/historico'
    | '/perfil/notificacoes'
    | '/taf/resultado'
    | '/taf/simulado'
    | '/treino/ativo'
    | '/treino/concluido'
    | '/api/public/mercadopago-webhook'
    | '/api/public/mp-public-key'
    | '/api/public/exercise-gif-by-name/$name'
    | '/api/public/exercise-gif/$id'
    | '/api/public/hooks/send-reminders'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/comunidade'
    | '/dieta'
    | '/evolucao'
    | '/exercicio-detalhe'
    | '/home'
    | '/loja'
    | '/nutricao'
    | '/perfil'
    | '/semana'
    | '/taf'
    | '/treino'
    | '/treino-do-dia'
    | '/treinos-so-barra'
    | '/trilha-barra'
    | '/upgrade'
    | '/auth/callback'
    | '/onboarding/caminho'
    | '/onboarding/email'
    | '/onboarding/equipamentos'
    | '/onboarding/frequencia'
    | '/onboarding/nivel'
    | '/onboarding/objetivo'
    | '/onboarding/previa'
    | '/onboarding/preview'
    | '/onboarding/processando'
    | '/perfil/dados'
    | '/perfil/historico'
    | '/perfil/notificacoes'
    | '/taf/resultado'
    | '/taf/simulado'
    | '/treino/ativo'
    | '/treino/concluido'
    | '/api/public/mercadopago-webhook'
    | '/api/public/mp-public-key'
    | '/api/public/exercise-gif-by-name/$name'
    | '/api/public/exercise-gif/$id'
    | '/api/public/hooks/send-reminders'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  ComunidadeRoute: typeof ComunidadeRoute
  DietaRoute: typeof DietaRoute
  EvolucaoRoute: typeof EvolucaoRoute
  ExercicioDetalheRoute: typeof ExercicioDetalheRoute
  HomeRoute: typeof HomeRoute
  LojaRoute: typeof LojaRoute
  NutricaoRoute: typeof NutricaoRoute
  PerfilRoute: typeof PerfilRouteWithChildren
  SemanaRoute: typeof SemanaRoute
  TafRoute: typeof TafRouteWithChildren
  TreinoRoute: typeof TreinoRouteWithChildren
  TreinoDoDiaRoute: typeof TreinoDoDiaRoute
  TreinosSoBarraRoute: typeof TreinosSoBarraRoute
  TrilhaBarraRoute: typeof TrilhaBarraRoute
  UpgradeRoute: typeof UpgradeRoute
  OnboardingCaminhoRoute: typeof OnboardingCaminhoRoute
  OnboardingEmailRoute: typeof OnboardingEmailRoute
  OnboardingEquipamentosRoute: typeof OnboardingEquipamentosRoute
  OnboardingFrequenciaRoute: typeof OnboardingFrequenciaRoute
  OnboardingNivelRoute: typeof OnboardingNivelRoute
  OnboardingObjetivoRoute: typeof OnboardingObjetivoRoute
  OnboardingPreviaRoute: typeof OnboardingPreviaRoute
  OnboardingPreviewRoute: typeof OnboardingPreviewRoute
  OnboardingProcessandoRoute: typeof OnboardingProcessandoRoute
  ApiPublicMercadopagoWebhookRoute: typeof ApiPublicMercadopagoWebhookRoute
  ApiPublicMpPublicKeyRoute: typeof ApiPublicMpPublicKeyRoute
  ApiPublicExerciseGifByNameNameRoute: typeof ApiPublicExerciseGifByNameNameRoute
  ApiPublicExerciseGifIdRoute: typeof ApiPublicExerciseGifIdRoute
  ApiPublicHooksSendRemindersRoute: typeof ApiPublicHooksSendRemindersRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upgrade': {
      id: '/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof UpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trilha-barra': {
      id: '/trilha-barra'
      path: '/trilha-barra'
      fullPath: '/trilha-barra'
      preLoaderRoute: typeof TrilhaBarraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treinos-so-barra': {
      id: '/treinos-so-barra'
      path: '/treinos-so-barra'
      fullPath: '/treinos-so-barra'
      preLoaderRoute: typeof TreinosSoBarraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treino-do-dia': {
      id: '/treino-do-dia'
      path: '/treino-do-dia'
      fullPath: '/treino-do-dia'
      preLoaderRoute: typeof TreinoDoDiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treino': {
      id: '/treino'
      path: '/treino'
      fullPath: '/treino'
      preLoaderRoute: typeof TreinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taf': {
      id: '/taf'
      path: '/taf'
      fullPath: '/taf'
      preLoaderRoute: typeof TafRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/semana': {
      id: '/semana'
      path: '/semana'
      fullPath: '/semana'
      preLoaderRoute: typeof SemanaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutricao': {
      id: '/nutricao'
      path: '/nutricao'
      fullPath: '/nutricao'
      preLoaderRoute: typeof NutricaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja': {
      id: '/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof LojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercicio-detalhe': {
      id: '/exercicio-detalhe'
      path: '/exercicio-detalhe'
      fullPath: '/exercicio-detalhe'
      preLoaderRoute: typeof ExercicioDetalheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evolucao': {
      id: '/evolucao'
      path: '/evolucao'
      fullPath: '/evolucao'
      preLoaderRoute: typeof EvolucaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dieta': {
      id: '/dieta'
      path: '/dieta'
      fullPath: '/dieta'
      preLoaderRoute: typeof DietaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidade': {
      id: '/comunidade'
      path: '/comunidade'
      fullPath: '/comunidade'
      preLoaderRoute: typeof ComunidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treino/concluido': {
      id: '/treino/concluido'
      path: '/concluido'
      fullPath: '/treino/concluido'
      preLoaderRoute: typeof TreinoConcluidoRouteImport
      parentRoute: typeof TreinoRoute
    }
    '/treino/ativo': {
      id: '/treino/ativo'
      path: '/ativo'
      fullPath: '/treino/ativo'
      preLoaderRoute: typeof TreinoAtivoRouteImport
      parentRoute: typeof TreinoRoute
    }
    '/taf/simulado': {
      id: '/taf/simulado'
      path: '/simulado'
      fullPath: '/taf/simulado'
      preLoaderRoute: typeof TafSimuladoRouteImport
      parentRoute: typeof TafRoute
    }
    '/taf/resultado': {
      id: '/taf/resultado'
      path: '/resultado'
      fullPath: '/taf/resultado'
      preLoaderRoute: typeof TafResultadoRouteImport
      parentRoute: typeof TafRoute
    }
    '/perfil/notificacoes': {
      id: '/perfil/notificacoes'
      path: '/notificacoes'
      fullPath: '/perfil/notificacoes'
      preLoaderRoute: typeof PerfilNotificacoesRouteImport
      parentRoute: typeof PerfilRoute
    }
    '/perfil/historico': {
      id: '/perfil/historico'
      path: '/historico'
      fullPath: '/perfil/historico'
      preLoaderRoute: typeof PerfilHistoricoRouteImport
      parentRoute: typeof PerfilRoute
    }
    '/perfil/dados': {
      id: '/perfil/dados'
      path: '/dados'
      fullPath: '/perfil/dados'
      preLoaderRoute: typeof PerfilDadosRouteImport
      parentRoute: typeof PerfilRoute
    }
    '/onboarding/processando': {
      id: '/onboarding/processando'
      path: '/onboarding/processando'
      fullPath: '/onboarding/processando'
      preLoaderRoute: typeof OnboardingProcessandoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/preview': {
      id: '/onboarding/preview'
      path: '/onboarding/preview'
      fullPath: '/onboarding/preview'
      preLoaderRoute: typeof OnboardingPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/previa': {
      id: '/onboarding/previa'
      path: '/onboarding/previa'
      fullPath: '/onboarding/previa'
      preLoaderRoute: typeof OnboardingPreviaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/objetivo': {
      id: '/onboarding/objetivo'
      path: '/onboarding/objetivo'
      fullPath: '/onboarding/objetivo'
      preLoaderRoute: typeof OnboardingObjetivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/nivel': {
      id: '/onboarding/nivel'
      path: '/onboarding/nivel'
      fullPath: '/onboarding/nivel'
      preLoaderRoute: typeof OnboardingNivelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/frequencia': {
      id: '/onboarding/frequencia'
      path: '/onboarding/frequencia'
      fullPath: '/onboarding/frequencia'
      preLoaderRoute: typeof OnboardingFrequenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/equipamentos': {
      id: '/onboarding/equipamentos'
      path: '/onboarding/equipamentos'
      fullPath: '/onboarding/equipamentos'
      preLoaderRoute: typeof OnboardingEquipamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/email': {
      id: '/onboarding/email'
      path: '/onboarding/email'
      fullPath: '/onboarding/email'
      preLoaderRoute: typeof OnboardingEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/caminho': {
      id: '/onboarding/caminho'
      path: '/onboarding/caminho'
      fullPath: '/onboarding/caminho'
      preLoaderRoute: typeof OnboardingCaminhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/public/mp-public-key': {
      id: '/api/public/mp-public-key'
      path: '/api/public/mp-public-key'
      fullPath: '/api/public/mp-public-key'
      preLoaderRoute: typeof ApiPublicMpPublicKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mercadopago-webhook': {
      id: '/api/public/mercadopago-webhook'
      path: '/api/public/mercadopago-webhook'
      fullPath: '/api/public/mercadopago-webhook'
      preLoaderRoute: typeof ApiPublicMercadopagoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/send-reminders': {
      id: '/api/public/hooks/send-reminders'
      path: '/api/public/hooks/send-reminders'
      fullPath: '/api/public/hooks/send-reminders'
      preLoaderRoute: typeof ApiPublicHooksSendRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/exercise-gif/$id': {
      id: '/api/public/exercise-gif/$id'
      path: '/api/public/exercise-gif/$id'
      fullPath: '/api/public/exercise-gif/$id'
      preLoaderRoute: typeof ApiPublicExerciseGifIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/exercise-gif-by-name/$name': {
      id: '/api/public/exercise-gif-by-name/$name'
      path: '/api/public/exercise-gif-by-name/$name'
      fullPath: '/api/public/exercise-gif-by-name/$name'
      preLoaderRoute: typeof ApiPublicExerciseGifByNameNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PerfilRouteChildren {
  PerfilDadosRoute: typeof PerfilDadosRoute
  PerfilHistoricoRoute: typeof PerfilHistoricoRoute
  PerfilNotificacoesRoute: typeof PerfilNotificacoesRoute
}

const PerfilRouteChildren: PerfilRouteChildren = {
  PerfilDadosRoute: PerfilDadosRoute,
  PerfilHistoricoRoute: PerfilHistoricoRoute,
  PerfilNotificacoesRoute: PerfilNotificacoesRoute,
}

const PerfilRouteWithChildren =
  PerfilRoute._addFileChildren(PerfilRouteChildren)

interface TafRouteChildren {
  TafResultadoRoute: typeof TafResultadoRoute
  TafSimuladoRoute: typeof TafSimuladoRoute
}

const TafRouteChildren: TafRouteChildren = {
  TafResultadoRoute: TafResultadoRoute,
  TafSimuladoRoute: TafSimuladoRoute,
}

const TafRouteWithChildren = TafRoute._addFileChildren(TafRouteChildren)

interface TreinoRouteChildren {
  TreinoAtivoRoute: typeof TreinoAtivoRoute
  TreinoConcluidoRoute: typeof TreinoConcluidoRoute
}

const TreinoRouteChildren: TreinoRouteChildren = {
  TreinoAtivoRoute: TreinoAtivoRoute,
  TreinoConcluidoRoute: TreinoConcluidoRoute,
}

const TreinoRouteWithChildren =
  TreinoRoute._addFileChildren(TreinoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ComunidadeRoute: ComunidadeRoute,
  DietaRoute: DietaRoute,
  EvolucaoRoute: EvolucaoRoute,
  ExercicioDetalheRoute: ExercicioDetalheRoute,
  HomeRoute: HomeRoute,
  LojaRoute: LojaRoute,
  NutricaoRoute: NutricaoRoute,
  PerfilRoute: PerfilRouteWithChildren,
  SemanaRoute: SemanaRoute,
  TafRoute: TafRouteWithChildren,
  TreinoRoute: TreinoRouteWithChildren,
  TreinoDoDiaRoute: TreinoDoDiaRoute,
  TreinosSoBarraRoute: TreinosSoBarraRoute,
  TrilhaBarraRoute: TrilhaBarraRoute,
  UpgradeRoute: UpgradeRoute,
  OnboardingCaminhoRoute: OnboardingCaminhoRoute,
  OnboardingEmailRoute: OnboardingEmailRoute,
  OnboardingEquipamentosRoute: OnboardingEquipamentosRoute,
  OnboardingFrequenciaRoute: OnboardingFrequenciaRoute,
  OnboardingNivelRoute: OnboardingNivelRoute,
  OnboardingObjetivoRoute: OnboardingObjetivoRoute,
  OnboardingPreviaRoute: OnboardingPreviaRoute,
  OnboardingPreviewRoute: OnboardingPreviewRoute,
  OnboardingProcessandoRoute: OnboardingProcessandoRoute,
  ApiPublicMercadopagoWebhookRoute: ApiPublicMercadopagoWebhookRoute,
  ApiPublicMpPublicKeyRoute: ApiPublicMpPublicKeyRoute,
  ApiPublicExerciseGifByNameNameRoute: ApiPublicExerciseGifByNameNameRoute,
  ApiPublicExerciseGifIdRoute: ApiPublicExerciseGifIdRoute,
  ApiPublicHooksSendRemindersRoute: ApiPublicHooksSendRemindersRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
